# Generated by Django 4.2.7 on 2023-11-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catastrofe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('ubicacion', models.CharField(max_length=150)),
            ],
        ),
    ]
